# Generated by Django 4.2.2 on 2023-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('categoria', models.CharField(choices=[('pasteleria', 'Pastelería'), ('panaderia', 'Panadería'), ('abarrotes', 'Abarrotes')], max_length=20)),
            ],
        ),
    ]
