# Generated by Django 4.2.2 on 2023-12-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('reposteria', 'Reposteria'), ('panaderia', 'Panadería'), ('abarrotes', 'Abarrotes')], max_length=20),
        ),
    ]
