# Generated by Django 4.2.2 on 2023-12-04 22:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('pasteleria', 'Pastelería'), ('panaderia', 'Panadería'), ('abarrotes', 'Abarrotes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=app.models.get_upload_path),
        ),
    ]
