# Generated by Django 4.2.2 on 2023-12-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_categoria_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('reposteria', 'Reposteria'), ('panaderia', 'Panadería'), ('abarrotes', 'Abarrotes')], max_length=20),
        ),
    ]
