# Generated by Django 4.2.2 on 2023-12-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto_stock_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(blank=True, max_length=25, null=True)),
                ('apellido_trabajador', models.CharField(blank=True, max_length=25, null=True)),
                ('email_trabajador', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_trabajador', models.IntegerField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('Administrador', 'administrador'), ('Vendedor', 'vendedor')], max_length=20)),
            ],
        ),
    ]
