# Generated by Django 4.2.2 on 2023-12-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
