# Generated by Django 4.2.2 on 2023-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, max_length=25, null=True)),
                ('apellido_cliente', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=9, null=True)),
                ('pedido', models.CharField(blank=True, max_length=450, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_trabajador',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
