# Generated by Django 4.2.2 on 2023-12-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_statistic_delete_accesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
